- bgkeeps_unit.lfm
- bgkeeps_unit.pas
bgkeeps_unit, clientheight & clientwidth revised.  Font details including ParentFont = False added to all checkbox oblects. Form re-arranged.
> Background Template details

- print_settings_unit.lfm
- print_settings_unit.pas
For some reason this now contains two of my commits, possibly because of your recent actions?
> Background templates plus Output elements

- chair_frame_unit.lfm
- chairs_unit.lfm
chairs_unit.lfm
FontHeight -20 amended to -13
"Left =" statements removed from inherited objects. chair_frame_unit.lfm
Autosize = tue added
> Experimental chairing form update

- chair_frame_unit.lfm
- chairs_unit.lfm
- heave_chairs.lfm
- shove_timber.lfm
- shove_timber.pas
column alignment in frame
group boxes corrected
> Font & Cosmetic changes

- dxf_unit.lfm
- dxf_unit.pas
+ export tab , added blue group title
+ rails tab, added blue group title
> Fixed broken title

- check_diffs_unit.lfm
- check_diffs_unit.pas
ParentFont = False
TGroupbox > Tpanel
(name groupbox > group, as flare_panel already existed)
> Cosmetic changes

- platform_unit.lfm
- platform_unit.pas
cured ts_platform_checkbox error
cosmetic changes
Tgroupbox > Tpanel
> checkbox correction+

- trackbed_unit.lfm
- trackbed_unit.pas
checkbox bug fixed by
cosmetic changes
groupbox > panel
> tabsheet revised

- platform_unit.pas
- trackbed_unit.pas
> fix negative default

- metric_unit.lfm
- metric_unit.pas
Tgroupbox > Tpanel
autoscroll = true
this form has datestamp...
> Cosmetic changes + form scaling bugfix

- mint_unit.lfm
- mint_unit.pas
> Mint_unit Cosmetic changes

- jigs_unit.lfm
- jigs_unit.pas
Tgroupbox > Tpanel
add ExtCtrls
> jigs_unit Cosmetic

- intersect_unit.lfm
- intersect_unit.pas
> intersect_unit Cosmetic

- gaps_unit.lfm
- gaps_unit.pas
> gaps_unit Cosmetic

- keep_select.pas
Fix out of bounds error in:-
procedure current_state
> Keep_select.pas bugfix

- map_clarity_unit.lfm
- map_clarity_unit.pas
Ensure parentfont = false
replace 4 Tgroupbox objects with Tpanel + Tlabel objects. edit 2 remaining Tgroupbox objects
> map_clarity_unit cosmetics

- map_clarity_unit.lfm
> map_clarity_uniy

- export_draw_unit.pas
- pdf_laz_unit.pas
- print_settings_unit.lfm
- print_settings_unit.pas
- print_unit.pas
infill colours and infill styles,.
line thickness
marker colour options
grid line and label options
diagram mode options
> output elements enhancements

- bgkeeps_unit.lfm
- bgkeeps_unit.pas
- colour_unit.lfm
- colour_unit.pas
- print_settings_unit.lfm
- print_settings_unit.pas
Add background templates colour  panels and other info
> Background details enhancements

- math_unit.pas
fill_mark() will now automatically expand the marks_list
if required.
> Make marks_list properly dynamic
